import { lazy } from 'react'
import type { TemplateDefinition } from './types'
import type { MenuTemplateProps } from './types'
import type { ComponentType } from 'react'
import type { TemplateId, TenantBranding } from '@core/domain/entities/Tenant'

export const TEMPLATE_DEFINITIONS: Record<TemplateId, TemplateDefinition> = {
  'dark-modern': {
    id: 'dark-modern',
    name: 'Dark Modern',
    description: 'Sofisticado y oscuro con efectos glassmorphism. Ideal para bares, restaurantes nocturnos y espacios premium.',
    tags: ['Moderno', 'Oscuro', 'Premium'],
    previewBg: '#0B0B0C',
    previewAccent: '#e11d48',
    previewStyle: 'dark',
  },
  'light-minimal': {
    id: 'light-minimal',
    name: 'Light Minimal',
    description: 'Limpio y minimalista sobre fondo blanco. Perfecto para cafés, restaurantes de autor y cocina de fusión.',
    tags: ['Minimalista', 'Limpio', 'Elegante'],
    previewBg: '#FFFFFF',
    previewAccent: '#2563eb',
    previewStyle: 'light',
  },
  'warm-bistro': {
    id: 'warm-bistro',
    name: 'Warm Bistro',
    description: 'Cálido y acogedor con tonos terracota. Perfecto para sodas, bistros y restaurantes familiares.',
    tags: ['Cálido', 'Acogedor', 'Tradicional'],
    previewBg: '#FDF6EC',
    previewAccent: '#d97706',
    previewStyle: 'warm',
  },
  'carta-negra': {
    id: 'carta-negra',
    name: 'Carta Negra',
    description: 'Alta cocina con tipografía clásica sobre fondo oscuro. El menú físico de diseñador, en digital.',
    tags: ['Fine Dining', 'Clásico', 'Elegante'],
    previewBg: '#0e0c0a',
    previewAccent: '#c9a84c',
    previewStyle: 'dark',
  },
  'menu-autor': {
    id: 'menu-autor',
    name: 'Menú de Autor',
    description: 'Estilo pergamino cálido con tipografía editorial. Ideal para bistros, sodas y cocina de autor.',
    tags: ['Rustic', 'Bistro', 'Pergamino'],
    previewBg: '#faf5eb',
    previewAccent: '#8b2635',
    previewStyle: 'warm',
  },
  'neon-ramen': {
    id: 'neon-ramen',
    name: 'Neon Ramen',
    description: 'Izakaya nocturno con letrero de neón y tipografía japonesa. Para ramen, sushi y cocina asiática urbana.',
    tags: ['Asiático', 'Nocturno', 'Urbano'],
    previewBg: '#1a1a1a',
    previewAccent: '#ff6b35',
    previewStyle: 'dark',
  },
  'taqueria-viva': {
    id: 'taqueria-viva',
    name: 'Taquería Viva',
    description: 'Vibrante y festivo con colores cálidos. Ideal para taquerías, cocinas mexicanas y street food.',
    tags: ['Mexicano', 'Festivo', 'Colorido'],
    previewBg: '#fef2e4',
    previewAccent: '#d74e09',
    previewStyle: 'warm',
  },
  'la-trattoria': {
    id: 'la-trattoria',
    name: 'La Trattoria',
    description: 'Trattoria italiana clásica con tipografía elegante y líderes punteados. Para restaurantes italianos y europeos.',
    tags: ['Italiano', 'Clásico', 'Bistro'],
    previewBg: '#f8ede3',
    previewAccent: '#c41e3a',
    previewStyle: 'warm',
  },
  'cafe-parisien': {
    id: 'cafe-parisien',
    name: 'Café Parisién',
    description: 'Elegancia art déco parisina. Para cafés de especialidad, brasseries y restaurantes de autor europeos.',
    tags: ['Francés', 'Art Déco', 'Elegante'],
    previewBg: '#faf6f1',
    previewAccent: '#2c3e50',
    previewStyle: 'light',
  },
  'burger-joint': {
    id: 'burger-joint',
    name: 'Burger Joint',
    description: 'Audaz y apetitoso con tarjetas grandes y colores potentes. Para hamburguesas, fast casual y comida americana.',
    tags: ['Americano', 'Bold', 'Casual'],
    previewBg: '#fff8e7',
    previewAccent: '#dd2c00',
    previewStyle: 'warm',
  },
  'sushi-zen': {
    id: 'sushi-zen',
    name: 'Sushi Zen',
    description: 'Minimalismo japonés con espacio en blanco generoso. Para sushi bars, restaurantes japoneses y cocina asiática premium.',
    tags: ['Japonés', 'Minimalista', 'Zen'],
    previewBg: '#ffffff',
    previewAccent: '#e11d3a',
    previewStyle: 'light',
  },
  'mediterraneo': {
    id: 'mediterraneo',
    name: 'Mediterráneo',
    description: 'Fresco y aireado con paleta azul mediterránea. Para restaurantes griegos, españoles y cocina de mar.',
    tags: ['Mediterráneo', 'Fresco', 'Marino'],
    previewBg: '#f0f7ff',
    previewAccent: '#1a6ec4',
    previewStyle: 'light',
  },
  'steakhouse': {
    id: 'steakhouse',
    name: 'Steakhouse',
    description: 'Madera oscura y cuero premium. Para parrillas, asadores y restaurantes de carnes premium.',
    tags: ['Parrilla', 'Premium', 'Oscuro'],
    previewBg: '#1a1206',
    previewAccent: '#c8842a',
    previewStyle: 'dark',
  },
  'vegan-garden': {
    id: 'vegan-garden',
    name: 'Vegan Garden',
    description: 'Verde orgánico y natural con tarjetas redondeadas. Para restaurantes veganos, health food y cocina plant-based.',
    tags: ['Vegano', 'Orgánico', 'Natural'],
    previewBg: '#f0f7ed',
    previewAccent: '#3a7d44',
    previewStyle: 'light',
  },
  'retro-diner': {
    id: 'retro-diner',
    name: 'Retro Diner',
    description: 'Años 50 americano con tipografía retro y acentos rojo-blanco. Para diners, hamburgueserías vintage y cafeterías.',
    tags: ['Retro', 'Americano', 'Vintage'],
    previewBg: '#ffffff',
    previewAccent: '#d32f2f',
    previewStyle: 'light',
  },
  'artisan-coffee': {
    id: 'artisan-coffee',
    name: 'Artisan Coffee',
    description: 'Kraft paper y café de especialidad con tonos tierra. Para cafeterías de especialidad, roasters y brunch spots.',
    tags: ['Café', 'Artesanal', 'Kraft'],
    previewBg: '#e8dcc8',
    previewAccent: '#6f4e37',
    previewStyle: 'warm',
  },
  'pizza-rustica': {
    id: 'pizza-rustica',
    name: 'Pizza Rustica',
    description: 'Pizarrón de tiza sobre fondo oscuro. Para pizzerías, tratorias informales y cocina italiana casual.',
    tags: ['Pizzería', 'Pizarrón', 'Rústico'],
    previewBg: '#1c1008',
    previewAccent: '#e63b2e',
    previewStyle: 'dark',
  },
  'patisserie': {
    id: 'patisserie',
    name: 'Pâtisserie',
    description: 'Pastel dulce y elegante con detalles florales. Para pastelerías, cafés de postres y bakeries premium.',
    tags: ['Pastelería', 'Dulce', 'Floral'],
    previewBg: '#fff5f7',
    previewAccent: '#c2185b',
    previewStyle: 'light',
  },
  'wine-bodega': {
    id: 'wine-bodega',
    name: 'Wine Bodega',
    description: 'Carta de vinos en formato somelier con fondo borgoña. Para vinotecas, bodegas y restaurantes con carta de vinos.',
    tags: ['Vinos', 'Somelier', 'Premium'],
    previewBg: '#200d0d',
    previewAccent: '#a83225',
    previewStyle: 'dark',
  },
  'tapas-bar': {
    id: 'tapas-bar',
    name: 'Tapas Bar',
    description: 'Barra española cálida y compacta. Para bares de tapas, tabernas españolas y cocina mediterránea informal.',
    tags: ['Español', 'Tapas', 'Bar'],
    previewBg: '#fdf0d9',
    previewAccent: '#a0522d',
    previewStyle: 'warm',
  },
  'soda-tica': {
    id: 'soda-tica',
    name: 'Soda Tica',
    description: 'Calidez tica con acento Pura Vida. Ideal para sodas, casados y cocina costarricense tradicional.',
    tags: ['Tico', 'Casual', 'Familiar'],
    previewBg: '#f0f7ec',
    previewAccent: '#2d7a30',
    previewStyle: 'light',
  },
  'marisqueria': {
    id: 'marisqueria',
    name: 'Marisquería',
    description: 'Diseño marino profundo con olas y frescura atlántica. Para marisquerías, cevicherías y cocina de mar.',
    tags: ['Mariscos', 'Marino', 'Fresco'],
    previewBg: '#e8f4fc',
    previewAccent: '#0077aa',
    previewStyle: 'light',
  },
  'cevicheria': {
    id: 'cevicheria',
    name: 'Cevichería',
    description: 'Vibrante y cítrico con energía tropical. Para cevicherías, cocina peruana y platos frescos del mar.',
    tags: ['Ceviche', 'Cítrico', 'Vibrante'],
    previewBg: '#f0fdf4',
    previewAccent: '#16a34a',
    previewStyle: 'light',
  },
  'comida-corrida': {
    id: 'comida-corrida',
    name: 'Comida Corrida',
    description: 'Menú del día claro y eficiente. Perfecto para restaurantes de almuerzo, fondas y comida corrida LATAM.',
    tags: ['Almuerzo', 'LATAM', 'Económico'],
    previewBg: '#fff8f0',
    previewAccent: '#c0392b',
    previewStyle: 'warm',
  },
  'panaderia': {
    id: 'panaderia',
    name: 'Panadería',
    description: 'Calidez artesanal con tipografía serif y tonos trigo. Para panaderías, pastelerías y cafés de pan horneado.',
    tags: ['Pan', 'Artesanal', 'Cálido'],
    previewBg: '#fef9ee',
    previewAccent: '#b8770b',
    previewStyle: 'warm',
  },
  'heladeria': {
    id: 'heladeria',
    name: 'Heladería',
    description: 'Colores pastel vibrantes y energía festiva. Para heladerías, nevados y tiendas de postres fríos.',
    tags: ['Helados', 'Pastel', 'Divertido'],
    previewBg: '#fdf0ff',
    previewAccent: '#c026d3',
    previewStyle: 'light',
  },
}

export const TEMPLATE_DEFAULT_BRANDING: Record<TemplateId, Pick<TenantBranding, 'backgroundColor' | 'primaryColor' | 'fontFamily'>> = {
  'dark-modern': {
    backgroundColor: '#0B0B0C',
    primaryColor: '#e11d48',
    fontFamily: 'Inter',
  },
  'light-minimal': {
    backgroundColor: '#ffffff',
    primaryColor: '#2563eb',
    fontFamily: 'DM Sans',
  },
  'warm-bistro': {
    backgroundColor: '#FDF6EC',
    primaryColor: '#d97706',
    fontFamily: 'Playfair Display',
  },
  'carta-negra': {
    backgroundColor: '#0e0c0a',
    primaryColor: '#c9a84c',
    fontFamily: 'Playfair Display',
  },
  'menu-autor': {
    backgroundColor: '#faf5eb',
    primaryColor: '#8b2635',
    fontFamily: 'Playfair Display',
  },
  'neon-ramen': {
    backgroundColor: '#1a1a1a',
    primaryColor: '#ff6b35',
    fontFamily: 'Inter',
  },
  'taqueria-viva': {
    backgroundColor: '#fef2e4',
    primaryColor: '#d74e09',
    fontFamily: 'Nunito',
  },
  'la-trattoria': {
    backgroundColor: '#f8ede3',
    primaryColor: '#c41e3a',
    fontFamily: 'Playfair Display',
  },
  'cafe-parisien': {
    backgroundColor: '#faf6f1',
    primaryColor: '#2c3e50',
    fontFamily: 'Playfair Display',
  },
  'burger-joint': {
    backgroundColor: '#fff8e7',
    primaryColor: '#dd2c00',
    fontFamily: 'Outfit',
  },
  'sushi-zen': {
    backgroundColor: '#ffffff',
    primaryColor: '#e11d3a',
    fontFamily: 'Inter',
  },
  'mediterraneo': {
    backgroundColor: '#f0f7ff',
    primaryColor: '#1a6ec4',
    fontFamily: 'Outfit',
  },
  'steakhouse': {
    backgroundColor: '#1a1206',
    primaryColor: '#c8842a',
    fontFamily: 'Playfair Display',
  },
  'vegan-garden': {
    backgroundColor: '#f0f7ed',
    primaryColor: '#3a7d44',
    fontFamily: 'Nunito',
  },
  'retro-diner': {
    backgroundColor: '#ffffff',
    primaryColor: '#d32f2f',
    fontFamily: 'Inter',
  },
  'artisan-coffee': {
    backgroundColor: '#e8dcc8',
    primaryColor: '#6f4e37',
    fontFamily: 'Playfair Display',
  },
  'pizza-rustica': {
    backgroundColor: '#1c1008',
    primaryColor: '#e63b2e',
    fontFamily: 'Inter',
  },
  'patisserie': {
    backgroundColor: '#fff5f7',
    primaryColor: '#c2185b',
    fontFamily: 'Playfair Display',
  },
  'wine-bodega': {
    backgroundColor: '#200d0d',
    primaryColor: '#a83225',
    fontFamily: 'Playfair Display',
  },
  'tapas-bar': {
    backgroundColor: '#fdf0d9',
    primaryColor: '#a0522d',
    fontFamily: 'Playfair Display',
  },
  'soda-tica': {
    backgroundColor: '#f0f7ec',
    primaryColor: '#2d7a30',
    fontFamily: 'Nunito',
  },
  'marisqueria': {
    backgroundColor: '#e8f4fc',
    primaryColor: '#0077aa',
    fontFamily: 'Outfit',
  },
  'cevicheria': {
    backgroundColor: '#f0fdf4',
    primaryColor: '#16a34a',
    fontFamily: 'Outfit',
  },
  'comida-corrida': {
    backgroundColor: '#fff8f0',
    primaryColor: '#c0392b',
    fontFamily: 'Nunito',
  },
  'panaderia': {
    backgroundColor: '#fef9ee',
    primaryColor: '#b8770b',
    fontFamily: 'Playfair Display',
  },
  'heladeria': {
    backgroundColor: '#fdf0ff',
    primaryColor: '#c026d3',
    fontFamily: 'Nunito',
  },
}

export const TEMPLATE_COMPONENTS: Record<TemplateId, ReturnType<typeof lazy<ComponentType<MenuTemplateProps>>>> = {
  'dark-modern': lazy(() => import('./DarkModernTemplate')),
  'light-minimal': lazy(() => import('./LightMinimalTemplate')),
  'warm-bistro': lazy(() => import('./WarmBistroTemplate')),
  'carta-negra': lazy(() => import('./CartaNegraTemplate')),
  'menu-autor': lazy(() => import('./MenuAutorTemplate')),
  'neon-ramen': lazy(() => import('./NeonRamenTemplate')),
  'taqueria-viva': lazy(() => import('./TaqueriaVivaTemplate')),
  'la-trattoria': lazy(() => import('./LaTrattoriaTemplate')),
  'cafe-parisien': lazy(() => import('./CafeParisienTemplate')),
  'burger-joint': lazy(() => import('./BurgerJointTemplate')),
  'sushi-zen': lazy(() => import('./SushiZenTemplate')),
  'mediterraneo': lazy(() => import('./MediterraneoTemplate')),
  'steakhouse': lazy(() => import('./SteakhouseTemplate')),
  'vegan-garden': lazy(() => import('./VeganGardenTemplate')),
  'retro-diner': lazy(() => import('./RetroDinerTemplate')),
  'artisan-coffee': lazy(() => import('./ArtisanCoffeeTemplate')),
  'pizza-rustica': lazy(() => import('./PizzaRusticaTemplate')),
  'patisserie': lazy(() => import('./PatisserieTemplate')),
  'wine-bodega': lazy(() => import('./WineBodegaTemplate')),
  'tapas-bar': lazy(() => import('./TapasBarTemplate')),
  'soda-tica': lazy(() => import('./SodaTicaTemplate')),
  'marisqueria': lazy(() => import('./MarisqueriaTemplate')),
  'cevicheria': lazy(() => import('./CevicheriaTemplate')),
  'comida-corrida': lazy(() => import('./ComidaCorraidaTemplate')),
  'panaderia': lazy(() => import('./PanaderiaTemplate')),
  'heladeria': lazy(() => import('./HeladeriaTemplate')),
}

export const DEFAULT_TEMPLATE_ID: TemplateId = 'dark-modern'

export function getTemplateComponent(id: string): ReturnType<typeof lazy<ComponentType<MenuTemplateProps>>> {
  return TEMPLATE_COMPONENTS[id as TemplateId] ?? TEMPLATE_COMPONENTS[DEFAULT_TEMPLATE_ID]
}

export function getTemplateDefinition(id: string): TemplateDefinition {
  return TEMPLATE_DEFINITIONS[id as TemplateId] ?? TEMPLATE_DEFINITIONS[DEFAULT_TEMPLATE_ID]
}
